### ISSUE TITLE
Spotify Icon pure-white

### ISSUE THREAD

**Issue by aeforste** [perfect-things/perfect-home-themes#1]
I'm pretty new to github so I hope this is the right place for this. I wanted a Spotify icon available for the pure-white theme so I found one. Could you add it?

![spotify_logo](https://user-images.githubusercontent.com/23464030/93008058-4e088e00-f525-11ea-8703-cf2f7aa2b1e3.png)

**Comment by tborychowski** [comment]
Thanks, it's in now: https://github.com/perfect-things/perfect-home-themes/blob/master/theme-pure-white/spotify.png
